name: Deploy production by AWS Amplify
on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [released]
permissions: read-all # This is required to read the secrets
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions: read-all # This is required to read the secrets
    steps:
      - name: deploy
        run: |
          URL="${{ secrets.PRODUCTION_DEPLOY_WEBHOOK }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
